name: Hourly Update

on: 
  schedule:
    - cron: "0 * * * *"
  repository_dispatch:
    types: manual

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout our repository
        uses: actions/checkout@v3
      - name: Remove old wp files
        shell: bash
        run: |
          find . -maxdepth 1 -name wp-\* -exec rm -fr {} \;
          rm index.php license.txt readme.html xmlrpc.php
      - name: Checkout their repository
        uses: actions/checkout@v3
        with:
          repository: 'WordPress/WordPress'
          path: src
      - name: Get Previous tag
        working-directory: ./src
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Switch Tag
        working-directory: ./src
        shell: bash
        run: |
          git checkout tags/${{ steps.previoustag.outputs.tag }}
      - name: copy new files
        shell: bash
        run: |
          rsync -avzh ./src/ .
      - name: Commit changes
        shell: bash
        run: |
          LONG_HASH="$(git status | grep -o [a-z0-9] | tr -d "\n")"
          SHORT_HASH="${LONG_HASH:0:7}"
          git config http.sslVerify false
          git config user.name "Automated Push"
          git config user.email "actions@users.noreply.github.com"
          git status
          git add -A
          git commit -m "WordPress Tag: ${{ steps.previoustag.outputs.tag }}" || exit 0
      - name: Push changes
        shell: bash
        run: |
          REMOTE_REPO="https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          git push "${REMOTE_REPO}" HEAD:master