name: Push site to GridPane

on: push

jobs:
  sftp:

    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Rsync Deployment
        uses: Burnett01/rsync-deployments@5.2
        with:
          switches: -vrog --delete --chown=${{ secrets.GP_USER }}:${{ secrets.GP_USER }}
          path: ./
          remote_path: /home/${{ secrets.GP_USER }}/sites/${{ secrets.GP_SITE_URL }}/htdocs
          remote_host: ${{ secrets.GP_HOST }}
          remote_port: ${{ secrets.GP_HOST_PORT }}
          remote_user: root
          remote_key: ${{ secrets.GP_DEPLOY_KEY }}